/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class CustomerDetailsButtonForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDetailsButtonForm
     */
    public CustomerDetailsButtonForm() {
        initComponents();
        setSize(1440,1025);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTrains = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/d.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 0, 1110, 1024);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/Frame.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 260, 150);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/trainLabel.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 430, 90, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/tabler_brand-booking (1).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 580, 80, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/dashicons_tickets-alt.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 710, 90, 80);

        btnTrains.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        btnTrains.setForeground(new java.awt.Color(5, 51, 111));
        btnTrains.setText("TRAINS");
        btnTrains.setBorder(null);
        btnTrains.setBorderPainted(false);
        btnTrains.setContentAreaFilled(false);
        btnTrains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrainsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrainsMouseExited(evt);
            }
        });
        btnTrains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainsActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrains);
        btnTrains.setBounds(90, 440, 130, 60);

        btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(5, 51, 111));
        btnBooking.setText("BOOKING");
        btnBooking.setBorder(null);
        btnBooking.setBorderPainted(false);
        btnBooking.setContentAreaFilled(false);
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        jPanel1.add(btnBooking);
        btnBooking.setBounds(100, 590, 130, 50);

        btnTickets.setBackground(new java.awt.Color(42, 134, 251));
        btnTickets.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        btnTickets.setForeground(new java.awt.Color(5, 51, 111));
        btnTickets.setText("TICKETS");
        btnTickets.setBorder(null);
        btnTickets.setBorderPainted(false);
        btnTickets.setContentAreaFilled(false);
        btnTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicketsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicketsMouseExited(evt);
            }
        });
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });
        jPanel1.add(btnTickets);
        btnTickets.setBounds(100, 730, 120, 50);

        jButton5.setBackground(new java.awt.Color(42, 134, 251));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/material-symbols_logout-rounded.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(100, 880, 110, 90);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/c.png"))); // NOI18N
        btnUser.setBorder(null);
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        jPanel1.add(btnUser);
        btnUser.setBounds(100, 220, 120, 100);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 260, 75, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainsActionPerformed
        // TODO add your handling code here:
        TrainButtonForm a=new TrainButtonForm();
        a.setVisible(true);
        
    }//GEN-LAST:event_btnTrainsActionPerformed

    private void btnTrainsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainsMouseEntered
        // TODO add your handling code here:
        
        btnTrains.setContentAreaFilled(true);
        btnTrains.setBackground(Color.green);
    }//GEN-LAST:event_btnTrainsMouseEntered

    private void btnTrainsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrainsMouseExited
        // TODO add your handling code here:
        btnTrains.setBackground(new java.awt.Color(42, 134, 251));
        btnTrains.setContentAreaFilled(false);
        
                                                

   
    }//GEN-LAST:event_btnTrainsMouseExited

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
        BookingButtonForm b=new BookingButtonForm();
        b.setVisible(true);
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered

        btnBooking.setContentAreaFilled(true);
        btnBooking.setBackground(Color.green);
    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        btnBooking.setBackground(new java.awt.Color(42, 134, 251));
        btnBooking.setContentAreaFilled(false);
        
    
    }//GEN-LAST:event_btnBookingMouseExited

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        // TODO add your handling code here:
        TicketButtonForm t=new TicketButtonForm();
        t.setVisible(true);
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnTicketsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseEntered
        // TODO add your handling code here:
     
        btnTickets.setContentAreaFilled(true);
        btnTickets.setBackground(Color.green);
    }//GEN-LAST:event_btnTicketsMouseEntered

    private void btnTicketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketsMouseExited
        // TODO add your handling code here:
        btnTickets.setBackground(new java.awt.Color(42, 134, 251));
        btnTickets.setContentAreaFilled(false);
        
    }//GEN-LAST:event_btnTicketsMouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsButtonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetailsButtonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnTickets;
    private javax.swing.JButton btnTrains;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
