/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import model.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class registration extends javax.swing.JFrame {
    
    Statement stmt=null;
    Connection conn=null;
    DefaultTableModel dtm;
    ResultSet rs;
    PreparedStatement pst;
     
    

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_password1 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_number = new javax.swing.JLabel();
        lbl_repassword = new javax.swing.JLabel();
        txt_number = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_repassword = new javax.swing.JTextField();
        btn_already = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        png_rectangle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(42, 134, 251));
        jPanel1.setLayout(null);

        lbl_name.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name.setText("Username");
        lbl_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_name);
        lbl_name.setBounds(660, 280, 160, 37);

        lbl_password1.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        lbl_password1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password1.setText("Set Password");
        lbl_password1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_password1);
        lbl_password1.setBounds(620, 610, 230, 37);

        lbl_email.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email.setText("Email");
        lbl_email.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_email);
        lbl_email.setBounds(610, 500, 230, 37);

        lbl_number.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        lbl_number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_number.setText("Phone Number");
        lbl_number.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_number);
        lbl_number.setBounds(620, 390, 230, 37);

        lbl_repassword.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        lbl_repassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_repassword.setText("Confirm Password");
        lbl_repassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_repassword);
        lbl_repassword.setBounds(610, 720, 270, 37);

        txt_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_number);
        txt_number.setBounds(530, 430, 399, 57);

        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_email);
        txt_email.setBounds(530, 540, 399, 57);

        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_username);
        txt_username.setBounds(530, 320, 399, 57);

        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_password);
        txt_password.setBounds(530, 650, 399, 57);

        txt_repassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_repassword);
        txt_repassword.setBounds(530, 760, 399, 57);

        btn_already.setBackground(new java.awt.Color(42, 134, 251));
        btn_already.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        btn_already.setForeground(new java.awt.Color(255, 255, 255));
        btn_already.setText("Already registered? click here!");
        btn_already.setBorder(null);
        btn_already.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_already.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alreadyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_already);
        btn_already.setBounds(610, 940, 216, 19);

        btn_signup.setBackground(new java.awt.Color(0, 153, 0));
        btn_signup.setFont(new java.awt.Font("Georgia", 0, 32)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setText("SIGN UP");
        btn_signup.setBorder(null);
        btn_signup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signup);
        btn_signup.setBounds(615, 862, 210, 61);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(620, 58, 200, 200);

        png_rectangle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        png_rectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/rectangle.png"))); // NOI18N
        png_rectangle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(png_rectangle);
        png_rectangle.setBounds(169, 158, 1101, 734);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1460, 1024);

        setSize(new java.awt.Dimension(1456, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        
                     
         
            conn=MyConnection.dbConnect();
           
        
            String username= txt_username.getText();
            String phonenumber= txt_number.getText();
            String email =txt_email.getText();
            
            
           
            String setpassword=txt_password.getText();
            String retypepassword= txt_repassword.getText();
            
            
            try {
    int number = Integer.parseInt(phonenumber);
    // Validate the 'number' value falls within the allowable range
    // Perform the insert operation using the validated 'number' value
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid phone number", "Error", JOptionPane.ERROR_MESSAGE);
    return; // or handle the error appropriately
}

            
try {
    stmt = conn.createStatement();

    // Check if the number is already registered
    String checkQuery = "SELECT * FROM register WHERE NUMBER = '" + phonenumber + "'";
    ResultSet resultSet = stmt.executeQuery(checkQuery);
    if (resultSet.next()) {
        // Number is already registered
        JOptionPane.showMessageDialog(this, "Number is already registered", "Error", JOptionPane.ERROR_MESSAGE);
    } 
//    if(username=="" || phonenumber=="" || email=="" || setpassword==""|| retypepassword=="" ){
//        JOptionPane.showMessageDialog(this, "Fill every entry field", "Error", JOptionPane.ERROR_MESSAGE);
//        
//        
//    }
    else {
        // Number is not registered, proceed with account creation
        if (setpassword.equals(retypepassword)) {
            String sql = "INSERT INTO register (USERNAME,NUMBER , EMAIL, PASSWORD, CONFIRM_PASSWORD) VALUES ('" + username+ "','" + phonenumber  + "','" + email + "','" + setpassword + "','" + retypepassword + "')";

            stmt.executeUpdate(sql);
            System.out.println("Data inserted");
            JOptionPane.showMessageDialog(this, "Form submitted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            txt_email.setText("");
            txt_number.setText("");
            txt_password.setText("");
            txt_repassword.setText("");
            txt_username.setText("");
            
        } else {
            JOptionPane.showMessageDialog(this, "PASSWORD DOES NOT MATCH CONFIRM PASSWORD", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
} catch (Exception e) {
    System.out.println(e.getMessage());
}
        
//        login s= new login();
//        s.setVisible(true);
//        this.hide();
        
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_alreadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alreadyActionPerformed
        // TODO add your handling code here:
        login s= new login();
        s.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_alreadyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_already;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_number;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_repassword;
    private javax.swing.JLabel png_rectangle;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_repassword;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
